//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.0.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Constants</summary>
	[PublishedModel("constants")]
	public partial class Constants : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const string ModelTypeAlias = "constants";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new static PublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Constants, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Constants(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Design bending capacity of T-rail
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("designBendingCapacity")]
		public int DesignBendingCapacity => this.Value<int>("designBendingCapacity");

		///<summary>
		/// E_max
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("e_max")]
		public int E_max => this.Value<int>("e_max");

		///<summary>
		/// E_min
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("e_min")]
		public int E_min => this.Value<int>("e_min");

		///<summary>
		/// Excentricity of self-weight
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("excentricityOfSelfWeight")]
		public int ExcentricityOfSelfWeight => this.Value<int>("excentricityOfSelfWeight");

		///<summary>
		/// Layers number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("layersNumber")]
		public int LayersNumber => this.Value<int>("layersNumber");

		///<summary>
		/// Lenght waste
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("lenghtWaste")]
		public decimal LenghtWaste => this.Value<decimal>("lenghtWaste");

		///<summary>
		/// Max. base rail length
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("maxBaseRailLength")]
		public int MaxBaseRailLength => this.Value<int>("maxBaseRailLength");

		///<summary>
		/// Min. distance between brackets
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("minDistanceBetweenBrackets")]
		public int MinDistanceBetweenBrackets => this.Value<int>("minDistanceBetweenBrackets");

		///<summary>
		/// - 4 Screws
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("screwsFour")]
		public decimal ScrewsFour => this.Value<decimal>("screwsFour");

		///<summary>
		/// - 2 Screws
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("screwsTwo")]
		public decimal ScrewsTwo => this.Value<decimal>("screwsTwo");
	}
}
