//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.0.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Link Calculator</summary>
	[PublishedModel("linkCalculator")]
	public partial class LinkCalculator : Common
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const string ModelTypeAlias = "linkCalculator";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new static PublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LinkCalculator, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public LinkCalculator(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Add new type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("addNewType")]
		public string AddNewType => this.Value<string>("addNewType");

		///<summary>
		/// Angle brackets
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("angleBrackets")]
		public string AngleBrackets => this.Value<string>("angleBrackets");

		///<summary>
		/// Board LBM
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("boardLBM")]
		public string BoardLbm => this.Value<string>("boardLBM");

		///<summary>
		/// Calculator Tilte
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("CalculatorPageTilte")]
		public string CalculatorPageTilte => this.Value<string>("CalculatorPageTilte");

		///<summary>
		/// Corner brackets
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("cornerBrackets")]
		public string CornerBrackets => this.Value<string>("cornerBrackets");

		///<summary>
		/// Delivered: Delivered m2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("delivered")]
		public string Delivered => this.Value<string>("delivered");

		///<summary>
		/// Delivered brackets
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("deliveredBrackets")]
		public string DeliveredBrackets => this.Value<string>("deliveredBrackets");

		///<summary>
		/// Delivered LBM: Delivered LBM (precut)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("deliveredLBM")]
		public string DeliveredLbm => this.Value<string>("deliveredLBM");

		///<summary>
		/// Delivered screws
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("deliveredScrews")]
		public string DeliveredScrews => this.Value<string>("deliveredScrews");

		///<summary>
		/// Door
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("door")]
		public string Door => this.Value<string>("door");

		///<summary>
		/// Heading ( Amount ): Column heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("headingAmount")]
		public string HeadingAmount => this.Value<string>("headingAmount");

		///<summary>
		/// Heading ( Amount )
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("headingAmountProducts")]
		public string HeadingAmountProducts => this.Value<string>("headingAmountProducts");

		///<summary>
		/// Heading (Brackets): Column heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("headingBrackets")]
		public string HeadingBrackets => this.Value<string>("headingBrackets");

		///<summary>
		/// Heading ( Calculations )
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("headingCalculations")]
		public string HeadingCalculations => this.Value<string>("headingCalculations");

		///<summary>
		/// Heading ( Description )
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("headingDescription")]
		public string HeadingDescription => this.Value<string>("headingDescription");

		///<summary>
		/// Heading ( Height ): Column heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("headingHeight")]
		public string HeadingHeight => this.Value<string>("headingHeight");

		///<summary>
		/// Heading (Information): Column heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("headingInformation")]
		public string HeadingInformation => this.Value<string>("headingInformation");

		///<summary>
		/// Heading (Installation Instructions): Heading of part named "Installation  Instructions"
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("headingInstallation")]
		public string HeadingInstallation => this.Value<string>("headingInstallation");

		///<summary>
		/// Heading ( Opening type ): Column heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("headingOpeningType")]
		public string HeadingOpeningType => this.Value<string>("headingOpeningType");

		///<summary>
		/// Heading (Opening types): Heading in the form
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("headingOpeningTypes")]
		public string HeadingOpeningTypes => this.Value<string>("headingOpeningTypes");

		///<summary>
		/// Heading ( Products )
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("headingProducts")]
		public string HeadingProducts => this.Value<string>("headingProducts");

		///<summary>
		/// Heading ( SAP No)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("headingSAPNo")]
		public string HeadingSapno => this.Value<string>("headingSAPNo");

		///<summary>
		/// Heading ( Width ): Column heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("headingWidth")]
		public string HeadingWidth => this.Value<string>("headingWidth");

		///<summary>
		/// Heading (Window/Door): Column heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("headingWindowDoor")]
		public string HeadingWindowDoor => this.Value<string>("headingWindowDoor");

		///<summary>
		/// Joiner brackets
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("joinerBrackets")]
		public string JoinerBrackets => this.Value<string>("joinerBrackets");

		///<summary>
		/// No delivered brackets message
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("noDeliveredBracketsMessage")]
		public string NoDeliveredBracketsMessage => this.Value<string>("noDeliveredBracketsMessage");

		///<summary>
		/// Description text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("openingTypesDescriptionText")]
		public IHtmlString OpeningTypesDescriptionText => this.Value<IHtmlString>("openingTypesDescriptionText");

		///<summary>
		/// Plank depth
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("plankDepth")]
		public string PlankDepth => this.Value<string>("plankDepth");

		///<summary>
		/// Precut planks text "no"
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("precutPlanksTextNo")]
		public string PrecutPlanksTextNo => this.Value<string>("precutPlanksTextNo");

		///<summary>
		/// Precut planks text "yes"
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("precutPlanksTextYes")]
		public string PrecutPlanksTextYes => this.Value<string>("precutPlanksTextYes");

		///<summary>
		/// End Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("resulterEndText")]
		public IHtmlString ResulterEndText => this.Value<IHtmlString>("resulterEndText");

		///<summary>
		/// Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("ResulterPageTilte")]
		public string ResulterPageTilte => this.Value<string>("ResulterPageTilte");

		///<summary>
		/// Select Form
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("selectForm")]
		public object SelectForm => this.Value("selectForm");

		///<summary>
		/// Self-weight: Self-weight per opening (kg)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("selfWeight")]
		public string SelfWeight => this.Value<string>("selfWeight");

		///<summary>
		/// Sum of needed LBM
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("sumOfNeededLBM")]
		public string SumOfNeededLbm => this.Value<string>("sumOfNeededLBM");

		///<summary>
		/// Used brackets
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("usedBrackets")]
		public string UsedBrackets => this.Value<string>("usedBrackets");

		///<summary>
		/// Used screws
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("usedScrews")]
		public string UsedScrews => this.Value<string>("usedScrews");

		///<summary>
		/// Window
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("window")]
		public string Window => this.Value<string>("window");
	}
}
