//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.0.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Link Constants</summary>
	[PublishedModel("linkConstants")]
	public partial class LinkConstants : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const string ModelTypeAlias = "linkConstants";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new static PublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LinkConstants, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public LinkConstants(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Additional corner screw minimum distance: in mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("additionalCornerScrewMinimumDistance")]
		public int AdditionalCornerScrewMinimumDistance => this.Value<int>("additionalCornerScrewMinimumDistance");

		///<summary>
		/// Additional corner screw spacing: in mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("additionalCornerScrewSpacing")]
		public int AdditionalCornerScrewSpacing => this.Value<int>("additionalCornerScrewSpacing");

		///<summary>
		/// Angle bracket threshold: in mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("angleBracketThreshold")]
		public int AngleBracketThreshold => this.Value<int>("angleBracketThreshold");

		///<summary>
		/// Board thickness: in mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("boardThickness")]
		public int BoardThickness => this.Value<int>("boardThickness");

		///<summary>
		/// Bracket thickness threshold: in mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("bracketThicknessThreshold")]
		public int BracketThicknessThreshold => this.Value<int>("bracketThicknessThreshold");

		///<summary>
		/// Corner Angle bracket criterium: in mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("cornerAngleBracketCriterium")]
		public int CornerAngleBracketCriterium => this.Value<int>("cornerAngleBracketCriterium");

		///<summary>
		/// Corner Angle bracket distance: in mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("cornerAngleBracketDistance")]
		public int CornerAngleBracketDistance => this.Value<int>("cornerAngleBracketDistance");

		///<summary>
		/// Cut waste: in mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("cutWaste")]
		public int CutWaste => this.Value<int>("cutWaste");

		///<summary>
		/// Density: in mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("density")]
		public int Density => this.Value<int>("density");

		///<summary>
		/// Door corners per door: in pieces
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("doorCornersPerDoor")]
		public int DoorCornersPerDoor => this.Value<int>("doorCornersPerDoor");

		///<summary>
		/// Insulation ( Max ): in mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("insulationMax")]
		public int InsulationMax => this.Value<int>("insulationMax");

		///<summary>
		/// Insulation ( Min ): in mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("insulationMin")]
		public int InsulationMin => this.Value<int>("insulationMin");

		///<summary>
		/// Joiner bracket distance: in mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("joinerBracketDistance")]
		public int JoinerBracketDistance => this.Value<int>("joinerBracketDistance");

		///<summary>
		/// Joiner bracket requirement: in mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("joinerBracketRequirement")]
		public int JoinerBracketRequirement => this.Value<int>("joinerBracketRequirement");

		///<summary>
		/// L-Bund_Max (0-200mm): in mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("lBund_Max0200mm")]
		public int LBund_Max0200mm => this.Value<int>("lBund_Max0200mm");

		///<summary>
		/// L-Bund_Max (201-350mm): in mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("lBund_Max201_350mm")]
		public int LBund_Max201_350mm => this.Value<int>("lBund_Max201_350mm");

		///<summary>
		/// Length waste: in %
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("lengthWaste")]
		public int LengthWaste => this.Value<int>("lengthWaste");

		///<summary>
		/// Max Window Height: in mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("maxWindowHeight")]
		public int MaxWindowHeight => this.Value<int>("maxWindowHeight");

		///<summary>
		/// Max Window Width: in mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("maxWindowWidth")]
		public int MaxWindowWidth => this.Value<int>("maxWindowWidth");

		///<summary>
		/// Window corners per window: in pieces
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("windowCornersPerWindow")]
		public int WindowCornersPerWindow => this.Value<int>("windowCornersPerWindow");
	}
}
